#!/usr/bin/env python3
"""Build BrightSudoku's mark.

Writes two files from one description of the geometry:

  tool/src/main/res/drawable/loading_text_icon.xml   the splash mark
  assets/icon.png                                    the same mark, for the README

The rest of the gi-os Light collection draws the first letter of the tool's name.
Sudoku cannot: BrightSolitaire already has the S, and two tools in the same
toolbox showing the same letter is worse than no letter. So this one draws what
the tool actually is — a three by three grid with one square filled — which needs
no font, which is why this script has no dependencies at all. It is stdlib only,
so it runs anywhere Python does.

    python3 tools/generate_icon.py
"""

import os
import struct
import sys
import zlib

# ---- geometry, in the drawable's 240x240 viewport --------------------------

VIEWPORT = 240
MARGIN = 44
SIDE = VIEWPORT - 2 * MARGIN          # 152
CELL = SIDE / 3.0
OUTER = 9.0                            # border thickness
INNER = 6.0                            # thickness of the two lines each way


def rectangles():
    """The mark as a list of (x, y, w, h), all axis-aligned.

    Everything is a filled rectangle rather than a stroked path. A stroke is
    centred on its line, so half of an outer stroke would sit outside the
    viewport and be clipped by an adaptive-icon mask at a different radius on
    every launcher. Rectangles put every edge exactly where it is asked for.
    """
    lo, hi = MARGIN, MARGIN + SIDE
    out = []

    # Border, as four bars rather than a stroked box.
    out.append((lo, lo, SIDE, OUTER))                       # top
    out.append((lo, hi - OUTER, SIDE, OUTER))               # bottom
    out.append((lo, lo, OUTER, SIDE))                       # left
    out.append((hi - OUTER, lo, OUTER, SIDE))               # right

    # The two lines each way that make it a sudoku grid rather than a box.
    for i in (1, 2):
        at = lo + CELL * i - INNER / 2
        out.append((at, lo, INNER, SIDE))                   # vertical
        out.append((lo, at, SIDE, INNER))                   # horizontal

    # One square filled, in the middle. Inset so it reads as a square inside a
    # cell rather than as a blob touching the rules around it.
    inset = 7.0
    cx = lo + CELL + INNER / 2 + inset
    cy = lo + CELL + INNER / 2 + inset
    size = CELL - INNER - 2 * inset
    out.append((cx, cy, size, size))

    return out


def path_data():
    """The rectangles as one SVG/vector path, each closed with Z."""
    parts = []
    for x, y, w, h in rectangles():
        parts.append(
            "M%.2f %.2fH%.2fV%.2fH%.2fZ" % (x, y, x + w, y + h, x)
        )
    return "".join(parts)


# ---- outputs ---------------------------------------------------------------

VECTOR = """<?xml version="1.0" encoding="utf-8"?>
<!--
    Overrides the drawable of the same name in sdk:client, which is the SDK's
    "loading..." splash mark. Resources in the application module take
    precedence over resources from a library module, so this needs no manifest
    change: LightOS tools have no launcher icon, and the splash is the one place
    a tool can show a mark of its own.

    Generated by tools/generate_icon.py. Do not edit by hand.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="240dp"
    android:height="240dp"
    android:viewportWidth="240"
    android:viewportHeight="240">
  <path
      android:pathData="%s"
      android:fillColor="#fff"
      android:fillType="nonZero"/>
</vector>
"""


def write_png(path, size=240):
    """The mark as a PNG: white on a solid black tile.

    The drawable above is white on nothing, which is right for the splash — it is
    drawn on the SDK's black loading screen. This one is for the README, where
    the page behind it is white in one theme and black in the other, and a mark
    with no ground of its own would vanish into one of them. So it carries the
    ground with it.

    Written by hand because the mark is rectangles on a grid: an image library
    would be a dependency bought for nothing, and this script staying stdlib-only
    is what lets anyone regenerate the icon without setting anything up.
    """
    scale = size / float(VIEWPORT)
    rects = [(x * scale, y * scale, w * scale, h * scale) for x, y, w, h in rectangles()]

    rows = []
    for y in range(size):
        row = bytearray(b"\x00")          # PNG filter byte: none
        for x in range(size):
            inside = any(
                rx <= x + 0.5 < rx + rw and ry <= y + 0.5 < ry + rh
                for rx, ry, rw, rh in rects
            )
            row += b"\xff\xff\xff\xff" if inside else b"\x00\x00\x00\xff"
        rows.append(bytes(row))

    raw = zlib.compress(b"".join(rows), 9)

    def chunk(tag, data):
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", raw)
    png += chunk(b"IEND", b"")

    with open(path, "wb") as f:
        f.write(png)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    drawable = os.path.join(
        root, "tool", "src", "main", "res", "drawable", "loading_text_icon.xml"
    )
    icon = os.path.join(root, "assets", "icon.png")

    os.makedirs(os.path.dirname(drawable), exist_ok=True)
    os.makedirs(os.path.dirname(icon), exist_ok=True)

    with open(drawable, "w") as f:
        f.write(VECTOR % path_data())
    write_png(icon)

    print("wrote %s" % os.path.relpath(drawable, root))
    print("wrote %s" % os.path.relpath(icon, root))
    return 0


if __name__ == "__main__":
    sys.exit(main())
